### ISSUE TITLE
Data types coming out of the db

### ISSUE THREAD

**Issue by mjtorn** [expobrain/django-postgres-geometry#2]
Hi!

When creating a box, it's ok to pass Points to the model constructor, but when queried the data comes back as text. Do you have plans to fix this? What would you accept in a PR; the use of regexps to transform the string into tuples/Points or do you have cleaner ideas?

Thanks!

**Comment by mjtorn** [comment]
This was a weird side effect of something, the code does do Point objects (running the PR #3 code works).

**Comment by jessemorton** [comment]
@mjtorn I'm getting this same issue. I see your PR #3 code and that took care of your ticket #1, but as described in your comment above, I'm seeing the data returned as text in the shell rather than Point objects, e.g.
```
>>> myObject.box
'(5,5),(0,0)'
```

Are you getting something different?

**Comment by jessemorton** [comment]
False alarm. My shell wasn't using the updated code. Now I'm getting point objects:
```
[<Point(5.0,5.0)>, <Point(0.0,0.0)>]
```
